export default {
  msg: '操作成功',
  code: 200,
  data: [
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 1,
      name: '全身情况',
      formName: null,
      type: '下拉框',
      dropdownType: '多选',
      hasRequired: true,
      hasInverseSelection: false,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: '请选择',
      placeholderContent: '请选择',
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 1,
          optionsName: '没问到',
          mutuallyExclusiveConditions: '2,3,4,5,6,7,8,9',
          mutuallyExclusiveCondition: [2, 3, 4, 5, 6, 7, 8, 9],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 2,
          optionsName: '否认特殊情况',
          mutuallyExclusiveConditions: '1',
          mutuallyExclusiveCondition: [1],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 3,
          optionsName: '感冒',
          mutuallyExclusiveConditions: '1',
          mutuallyExclusiveCondition: [1],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 4,
          optionsName: '发烧',
          mutuallyExclusiveConditions: '1',
          mutuallyExclusiveCondition: [1],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 5,
          optionsName: '哮喘',
          mutuallyExclusiveConditions: '1',
          mutuallyExclusiveCondition: [1],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 6,
          optionsName: '心脏病',
          mutuallyExclusiveConditions: '1',
          mutuallyExclusiveCondition: [1],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 7,
          optionsName: '血友病',
          mutuallyExclusiveConditions: '1',
          mutuallyExclusiveCondition: [1],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 8,
          optionsName: '癫痫',
          mutuallyExclusiveConditions: '1',
          mutuallyExclusiveCondition: [1],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 9,
          optionsName: '特殊儿童',
          mutuallyExclusiveConditions: '1',
          mutuallyExclusiveCondition: [1],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 2,
      name: '就诊经历',
      formName: null,
      type: '单选按钮',
      dropdownType: null,
      hasRequired: true,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 1,
          optionsName: '没问到',
          mutuallyExclusiveConditions: '2,3,4,5,6,7,8,9',
          mutuallyExclusiveCondition: [2, 3, 4, 5, 6, 7, 8, 9],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 10,
          optionsName: '孩子看过牙',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 11,
          optionsName: '孩子没看过牙',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 3,
      name: '外院建议',
      formName: null,
      type: '多行文本框',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: false,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '2',
      parentId: 2,
      parentOptionsIds: '10',
      parentOptionsId: [10],
      validationMessage: null,
      placeholderContent: '请输入',
      prompt: null,
      ruleValidation: null,
      maxLength: 500,
      delFlag: null,
      optionsList: []
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 4,
      name: '检查涂氟配合',
      formName: null,
      type: '单选按钮',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '2',
      parentId: 2,
      parentOptionsIds: '10',
      parentOptionsId: [10],
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 12,
          optionsName: '不确定',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 13,
          optionsName: '是',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 14,
          optionsName: '否',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 5,
      name: '操作配合',
      formName: null,
      type: '单选按钮',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '2',
      parentId: 2,
      parentOptionsIds: '10',
      parentOptionsId: [10],
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 12,
          optionsName: '不确定',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 13,
          optionsName: '是',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 14,
          optionsName: '否',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 6,
      name: '处理意愿',
      formName: null,
      type: '单选按钮',
      dropdownType: null,
      hasRequired: true,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 1,
          optionsName: '没问到',
          mutuallyExclusiveConditions: '2,3,4,5,6,7,8,9',
          mutuallyExclusiveCondition: [2, 3, 4, 5, 6, 7, 8, 9],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 15,
          optionsName: '当天处理',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 16,
          optionsName: '当天不着急处理',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 7,
      name: '不着急原因',
      formName: null,
      type: '多行文本框',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: false,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '2',
      parentId: 6,
      parentOptionsIds: '16',
      parentOptionsId: [16],
      validationMessage: null,
      placeholderContent: '请输入',
      prompt: null,
      ruleValidation: null,
      maxLength: 500,
      delFlag: null,
      optionsList: []
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 8,
      name: '预防意识',
      formName: null,
      type: '单选按钮',
      dropdownType: null,
      hasRequired: true,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 1,
          optionsName: '没问到',
          mutuallyExclusiveConditions: '2,3,4,5,6,7,8,9',
          mutuallyExclusiveCondition: [2, 3, 4, 5, 6, 7, 8, 9],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 17,
          optionsName: '做过预防',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 18,
          optionsName: '感兴趣（话题有互动）',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 19,
          optionsName: '不了解',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 9,
      name: '曾做项目',
      formName: null,
      type: '多选按钮',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '2',
      parentId: 8,
      parentOptionsIds: '17',
      parentOptionsId: [17],
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 20,
          optionsName: '涂氟',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 21,
          optionsName: '窝沟封闭',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 22,
          optionsName: '洗牙',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 23,
          optionsName: '检查',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 10,
      name: '价格接受度',
      formName: null,
      type: '单选按钮',
      dropdownType: null,
      hasRequired: true,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 24,
          optionsName: '未表达贵',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 25,
          optionsName: '表达贵',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 11,
      name: '沟通情况',
      formName: null,
      type: '单选按钮',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 26,
          optionsName: '主动询问',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 27,
          optionsName: '有问有答',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 28,
          optionsName: '勉强回应',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 29,
          optionsName: '着急挂电话',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 30,
          optionsName: '拒绝沟通',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 12,
      name: '决策人',
      formName: null,
      type: '多选按钮',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 12,
          optionsName: '不确定',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 32,
          optionsName: '妈妈',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 33,
          optionsName: '爸爸',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 34,
          optionsName: '外婆',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 35,
          optionsName: '外公',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 36,
          optionsName: '奶奶',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 37,
          optionsName: '爷爷',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 999,
          optionsName: '其他',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 13,
      name: '陪同情况',
      formName: null,
      type: '单选按钮',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: '',
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: '',
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 1,
          optionsName: '没问到',
          mutuallyExclusiveConditions: '2,3,4,5,6,7,8,9',
          mutuallyExclusiveCondition: [2, 3, 4, 5, 6, 7, 8, 9],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 38,
          optionsName: '决策人来',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 39,
          optionsName: '决策人可电联',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 40,
          optionsName: '决策人不可电联',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 14,
      name: '刷牙情况',
      formName: null,
      type: '单选按钮',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 1,
          optionsName: '没问到',
          mutuallyExclusiveConditions: '2,3,4,5,6,7,8,9',
          mutuallyExclusiveCondition: [2, 3, 4, 5, 6, 7, 8, 9],
          hasDisabled: false,
          color: '#FFFFFF',
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 41,
          optionsName: '不刷牙',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 42,
          optionsName: '刷牙',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 15,
      name: '刷牙配合',
      formName: null,
      type: '单选按钮',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '2',
      parentId: 14,
      parentOptionsIds: '999,32,33,34,35,36,37',
      parentOptionsId: [999, 32, 33, 34, 35, 36, 37],
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 12,
          optionsName: '不确定',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 13,
          optionsName: '是',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 14,
          optionsName: '否',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 16,
      name: '接诊介绍',
      formName: null,
      type: '多选按钮',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 43,
          optionsName: '未介绍',
          mutuallyExclusiveConditions: '44,45,46,47,48,49,50,51',
          mutuallyExclusiveCondition: [44, 45, 46, 47, 48, 49, 50, 51],
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 44,
          optionsName: '提前到诊',
          mutuallyExclusiveConditions: '43',
          mutuallyExclusiveCondition: [43],
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 45,
          optionsName: '填表可能',
          mutuallyExclusiveConditions: '43',
          mutuallyExclusiveCondition: [43],
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 46,
          optionsName: '拍片可能',
          mutuallyExclusiveConditions: '43',
          mutuallyExclusiveCondition: [43],
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 47,
          optionsName: '行为引导',
          mutuallyExclusiveConditions: '43',
          mutuallyExclusiveCondition: [43],
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 48,
          optionsName: '看诊时长',
          mutuallyExclusiveConditions: '43',
          mutuallyExclusiveCondition: [43],
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 49,
          optionsName: '当日处理',
          mutuallyExclusiveConditions: '43',
          mutuallyExclusiveCondition: [43],
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 50,
          optionsName: '内窥镜',
          mutuallyExclusiveConditions: '43',
          mutuallyExclusiveCondition: [43],
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 51,
          optionsName: '束缚可能',
          mutuallyExclusiveConditions: '43',
          mutuallyExclusiveCondition: [43],
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 17,
      name: '异议点',
      formName: null,
      type: '多选按钮',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: true,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: null,
      delFlag: null,
      optionsList: [
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 52,
          optionsName: '介意辐射',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 53,
          optionsName: '介意麻药',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 54,
          optionsName: '介意哭',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 55,
          optionsName: '介意束缚',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 56,
          optionsName: '担心不配合',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 57,
          optionsName: '担心孩子痛',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 58,
          optionsName: '治疗存疑',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 59,
          optionsName: '矫正存疑',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 60,
          optionsName: '医生资质/疗效水平',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 61,
          optionsName: '消费不透明',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 62,
          optionsName: '有免费/低价预防',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 63,
          optionsName: '拒绝带牙刷',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        },
        {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 999,
          optionsName: '其他',
          mutuallyExclusiveConditions: null,
          mutuallyExclusiveCondition: null,
          hasDisabled: false,
          color: null,
          optionTooltip: null,
          bubbleContent: null,
          delFlag: null
        }
      ]
    },
    {
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      id: 18,
      name: '其他备注',
      formName: null,
      type: '多行文本框',
      dropdownType: null,
      hasRequired: false,
      hasInverseSelection: false,
      hasMutuallyExclusive: false,
      hasDisabled: false,
      questionLevel: '1',
      parentId: null,
      parentOptionsIds: null,
      parentOptionsId: null,
      validationMessage: null,
      placeholderContent: null,
      prompt: null,
      ruleValidation: null,
      maxLength: 500,
      delFlag: null,
      optionsList: []
    }
  ]
}
